### ISSUE TITLE
Task-switcher (meta+W) does not respond to keyboard input

### ISSUE THREAD

**Issue by slartibart70** [ZaWertun/fedora-copr-kde5#135]
Hi, 
since last update i encounter a non-working keyboard in all of the 'present windows' functions of plasma. That is, toggle-overview (meta+w) and any present windows (meta-f7, meta-f9 and the like)
This was working already, mouse is ok, but not even the search input field is accepting any input (even if i select the field with the mouse)
Not even ESC is accepted, although pressing meta-w again leaves the toggle-overview

any ideas?

---

Operating System: Fedora Linux 36
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.5
Kernel Version: 5.19.9-200.fc36.x86_64 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31,1 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
Manufacturer: LENOVO
Product Name: 20J6003DGE
System Version: ThinkPad T470p

**Comment by ZaWertun** [comment]
Maybe some new bug... Can't reproduce on my PC though.
Try to test it with new user, maybe something was wrong in configuration files.

**Comment by ZaWertun** [comment]
Maybe this bug: https://bugs.kde.org/show_bug.cgi?id=459188 ?
(Wayland only, can't be reproduced on Xorg)

**Comment by ZaWertun** [comment]
Just checked my other PC with NVidia - I can confirm this bug happening.
Don't sure if it because using NVidia or what, on Intel (with X11) all is fine.

**Comment by ZaWertun** [comment]
Maybe related, running overview with NVidia spams with those messages:
```
ep 20 10:05:00 rapidus kwin_x11[3047]: file:///usr/lib64/qt5/qml/org/kde/kwin/private/effects/WindowHeap.qml:56:9: Unable to assign null to QUuid
Sep 20 10:05:00 rapidus kwin_x11[3047]: file:///usr/lib64/qt5/qml/org/kde/kwin/private/effects/WindowHeap.qml:56:9: Unable to assign null to QUuid
Sep 20 10:05:02 rapidus kwin_x11[3047]: file:///usr/share/kwin/effects/overview/qml/ScreenView.qml: Writing to "client" broke the binding to the underlying model
Sep 20 10:05:09 rapidus kwin_x11[3047]: file:///usr/lib64/qt5/qml/org/kde/kwin/private/effects/WindowHeap.qml:56:9: Unable to assign null to QUuid
Sep 20 10:05:09 rapidus kwin_x11[3047]: file:///usr/lib64/qt5/qml/org/kde/kwin/private/effects/WindowHeap.qml:56:9: Unable to assign null to QUuid
```

**Comment by ZaWertun** [comment]
Looks like this commit should fix it: https://invent.kde.org/plasma/kwin/-/commit/e6ae8fb6755398d3512863c7de6493360962118e.
I'll try it on my home PC first.

**Comment by ZaWertun** [comment]
@slartibart70 This patch helps me:
```patch
--- /usr/lib64/qt5/qml/org/kde/kwin/private/effects/WindowHeap.qml.orig 2022-09-20 10:23:00.392314248 +0300
+++ /usr/lib64/qt5/qml/org/kde/kwin/private/effects/WindowHeap.qml      2022-09-20 10:23:12.725415620 +0300
@@ -53,7 +53,7 @@
         z: 2
         property KWinComponents.WindowThumbnailItem cloneOf
         visible: false
-        wId: cloneOf ? cloneOf.wId : null
+        wId: cloneOf ? cloneOf.wId : "00000000-0000-0000-0000-000000000000"
         width: cloneOf ? cloneOf.width : 0
         height: cloneOf ? cloneOf.height : 0
         onCloneOfChanged: {
```
I'll rebuild kwin package little later.

**Comment by slartibart70** [comment]
Thanks for looking into this.
Strangely enough, it's back to a working state right now. One thing i did was to put the laptop to sleep overnight, and woke it up this morning. Overview effects are back to working (meta-w, meta-Fx), keyboard is ok, search-inputfield can be filled with characters
I'll try to figure out what happened when it occurred the first time (for reproducaibility)

**Comment by ZaWertun** [comment]
https://copr.fedorainfracloud.org/coprs/build/4866227

**Comment by ZaWertun** [comment]
Should be fixed in kwin-5.25.5-2.

**Comment by slartibart70** [comment]
Hi,
since this update in fc36, the keyboard navigation seems broken again for Ctrl-W, mouse still works
symptoms: neither cursor keys nor letter (for search) are available, ESC does not work any more 
Can you confirm?

Operating System: Fedora Linux 36
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.8
Kernel Version: 6.1.7-100.fc36.x86_64 (64-bit)
Graphics Platform: X11

**Comment by slartibart70** [comment]
update / need to clarify:
sometimes it's broken as described above. Now, after some longer screensaver period, it's ok again??
Very hard to track down what happened before. But maybe worth a look, that in some situations Meta-W does not react on any keypresses at all. Only mouse is working.

**Comment by ZaWertun** [comment]
Can't confirm this issue happens on Fedora 37 with Nvidia proprietary drivers.
Tried it several times.

Check kwin logs maybe there is some new errors.

**Comment by slartibart70** [comment]
the error is back
Meta-W, you see the overview, but none of the windows have the 'selected' surroundings (here, blue frame as visual indicator around the smaller views) which is movable with the cursor-keys. The keyboard is just dead in this situation.

I have `journalctl -f -b 0` open, but no errors appearing when going into Meta-W

I'll upgrade to fc37 anyway (later) but this is definitely annoying (you provided frameworks 102 only for fc37, so that would be THE reason to switch :-)

**Comment by slartibart70** [comment]
since fc37 upgrade, i did not encounter this problem any more.
Let's close it
