### ISSUE TITLE
Rebuild Plasma-pa with pipewire-pulseaudio as a possible dependency

### ISSUE THREAD

**Issue by mmcnutt** [ZaWertun/fedora-copr-kde5#59]
I'm wanting to test pipewire-pulseaudio as a replacement for pulseaudio (this is a proposed change for Fedora 34)

At the next rebuild can plasma-pa be built with this as a dependency? My packaging knowledge is limited, so I'm not sure how reasonable a request this is

thanks

**Comment by ZaWertun** [comment]
As far as I know pipiwire provides library 100% compatible with those one from pulseaudio.

So there is no need to rebuild applications.
From application side it looks like plain old pulseaudio lib.

**Comment by mmcnutt** [comment]
I'm confused then - When replacing pulse with pipewire-pulse it wants to remove plasma-pa, perhaps  it is the removal of the alsa plugins that is triggering that

**Comment by ZaWertun** [comment]
Yep, there is some strange conflicts with `pulseaudio-libs-glib2` in my case.
Even if I try to swap pulseaudio-libs with pipewire-pulseaudio I see this:
```shell
$ sudo LANGUAGE=en dnf swap pulseaudio-libs pipewire-pulseaudio
Last metadata expiration check: 0:45:59 ago on Чт 31 дек 2020 14:22:07.
Error:
Problem 1: problem with installed package simplescreenrecorder-0.4.2-3.fc33.x86_64
- package simplescreenrecorder-0.4.2-3.fc33.x86_64 requires libpulse.so.0()(64bit), but none of the providers can be installed
- package simplescreenrecorder-0.4.2-3.fc33.x86_64 requires libpulse.so.0(PULSE_0)(64bit), but none of the providers can be installed
- conflicting requests
Problem 2: problem with installed package steam-1.0.0.68-2.fc33.i686
- package steam-1.0.0.68-2.fc33.i686 requires pulseaudio-libs(x86-32), but none of the providers can be installed
- package steam-1.0.0.66-2.fc33.i686 requires pulseaudio-libs(x86-32), but none of the providers can be installed
- conflicting requests
Problem 3: problem with installed package pulseaudio-libs-glib2-14.0-2.fc33.x86_64
- package pipewire-pulseaudio-0.3.13-4.fc33.i686 conflicts with pulseaudio-libs-glib2 provided by pulseaudio-libs-glib2-14.0-2.fc33.x86_64
- package pipewire-pulseaudio-0.3.13-4.fc33.i686 conflicts with pulseaudio-libs-glib2 provided by pulseaudio-libs-glib2-13.99.2-1.fc33.x86_64
- conflicting requests
- package pipewire-pulseaudio-0.3.15-2.fc33.i686 conflicts with pulseaudio-libs-glib2 provided by pulseaudio-libs-glib2-14.0-2.fc33.x86_64
- package pipewire-pulseaudio-0.3.15-2.fc33.i686 conflicts with pulseaudio-libs-glib2 provided by pulseaudio-libs-glib2-13.99.2-1.fc33.x86_64
- package pipewire-pulseaudio-0.3.13-4.fc33.x86_64 conflicts with pulseaudio-libs-glib2 provided by pulseaudio-libs-glib2-14.0-2.fc33.x86_64
- package pipewire-pulseaudio-0.3.13-4.fc33.x86_64 conflicts with pulseaudio-libs-glib2 provided by pulseaudio-libs-glib2-13.99.2-1.fc33.x86_64
- package pipewire-pulseaudio-0.3.15-2.fc33.x86_64 conflicts with pulseaudio-libs-glib2 provided by pulseaudio-libs-glib2-14.0-2.fc33.x86_64
- package pipewire-pulseaudio-0.3.15-2.fc33.x86_64 conflicts with pulseaudio-libs-glib2 provided by pulseaudio-libs-glib2-13.99.2-1.fc33.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
```

And with `--allowerasin` dnf wants to nuke half of my system...

**Comment by ZaWertun** [comment]
I think it's better to wait release of Fedora 34.
We will hope transition to the pipewire-pulseaudio will be more polished.

**Comment by ZaWertun** [comment]
Try again, there is update for pipewire-pulseaudio, looks better now:
![изображение](https://user-images.githubusercontent.com/1080298/103459175-321c3880-4d1e-11eb-8888-260237c17c37.png)

**Comment by ZaWertun** [comment]
@mmcnutt ^^^

**Comment by mmcnutt** [comment]
it still wants to purge plasma-pa, which will leave plasma unable to control volume, right?

I spun up a F33 KDE VM and its a problem with the official package as well, we can probably close this, as its not inherent to your repo

**Comment by g6avk** [comment]
Yes, I tested this as well and as @mmcnutt mentioned volume control is lost. No volume widget is available and the Audio section is missing in system Settings. 
Reverted back for now as it is not an issue with your repo :)

**Comment by ZaWertun** [comment]
New build: https://copr.fedorainfracloud.org/coprs/build/1853127.

**Comment by ZaWertun** [comment]
Done. Try updating.

**Comment by g6avk** [comment]
Perfect, that updated fine and the Volume control there again. The Audio settings are back in System Settings and everything seems to be working OK on this box.

**Comment by g6avk** [comment]
OK, after a few hours running I noticed Plasma Session using 50% CPU so I backed out pipewire-pulseaudio but left the updated plasma-pa and CPU usage is back to normal (tested this twice now)
Lets see if anyone else notices this.

**Comment by mmcnutt** [comment]
I updated 2.5 hours ago, seems to have worked fine. Thanks

 I've had youtube and music playing in that time and not seeing the 50% plasma cpu spike

**Comment by g6avk** [comment]
@mmcnutt thanks for your update, I will test again this week and see if the high CPU happens again.

**Comment by g6avk** [comment]
OK, I think I found the cause of the "plasma-session" high CPU here, if I turn off the login notification sound all is good. 
Can anyone confirm this?

**Comment by pizzadude** [comment]
I don't know about your issue but I tried pipewire-pulseaudio and the latency was too high in some programs so I just reverted back to regular pulse for now.

**Comment by g6avk** [comment]
@pizzadude thanks for the info, like you I have gone back to Pulse now. Too many issues at the moment.

**Comment by ZaWertun** [comment]
Just switched to pipewire - all seems to be fine at the moment.
I even has no problems with my bluetooth headphones.

@g6avk what problems do you have?

**Comment by g6avk** [comment]
I now found the cause as mentioned previously,

If the Plasma Login sound is enabled the "Plasma-Session" will use 50% CPU as soon as the login has finished. If I disable the Login sound the CPU usage is normal. I have tested this a number of times now.

However like @pizzadude there are lag/latency issues compared to Pulse that is why I also reverted back to Pulse for now.

**Comment by ZaWertun** [comment]
> I now found the cause as mentioned previously,
> 
> If the Plasma Login sound is enabled the "Plasma-Session" will use 50% CPU as soon as the login has finished. If I disable the Login sound the CPU usage is normal. I have tested this a number of times now.
> 
> However like @pizzadude there are lag/latency issues compared to Pulse that is why I also reverted back to Pulse for now.

Long or short one? I'll try.

About latency - pipewire works now with default priority (0), while pulseaudio works with -11.
Because of that any heavy load on system can cause sound issues.
It's already fixed in the master and soon will be available in new version.

**Comment by ZaWertun** [comment]
Yep, can confirm about login sound.
After enabling it I see that process `plasma_session` uses 35-50% of 1 CPU core constantly.

**Comment by g6avk** [comment]
OK, thanks for confirming 👍🏻 is it a Plasma or Pipewire bug I wonder.. I'll will try and do more research later on.

**Comment by pizzadude** [comment]
With latest pipewire the latency problems are gone for me. However it still doesn't have feature parity with pulseaudio, advanced stuff like pulseaudio-dlna or stuff relying module-loopback don't work yet.. :P
